### ISSUE TITLE
Create init script to start and stop the bot

### ISSUE THREAD

**Issue by q0rban** [Lullabot/lubot#12]
We need an init script to start and stop the bot.

**Comment by willwh** [comment]
Check out [pm2](https://github.com/Unitech/pm2)

```
sudo npm install -g pm2 && pm2 startup
```

I'm running the [drupalize.me branch of lubot](https://github.com/Lullabot/lubot/tree/drupalize.me) with it

**Comment by q0rban** [comment]
Nice!

**Comment by sirkitree** [comment]
yeah i've been using this on a project of mine as well, it's pretty great.
