### ISSUE TITLE
Integrate with Hangouts API

### ISSUE THREAD

**Issue by q0rban** [Lullabot/lubot#13]
Would be really cool if we could integrate with the hangouts api, to do things like:

```
q0rban> Hey justafish, want to chat about this irc bot?
justafish> sure!
q0rban> justafish: hangout?
lubot> q0rban, justafish: here you go: https://plus.google.com/hangouts/_/7acpilptuelr08i6uh7ct69clk?hl=en
```

**Comment by m4olivei** [comment]
This might be something to look at as a basis for doing this: https://github.com/suda/slack-hangout.  It's a /hangout slack command before there was an official one.
