### ISSUE TITLE
Integrate with Hackpad API

### ISSUE THREAD

**Issue by q0rban** [Lullabot/lubot#14]
Would be cool if we could integrate with Hackpad API to do things like search for pads, create a new pad.

https://hackpad.com/Hackpad-API-v1.0-k9bpcEeOo2Q

**Comment by willwh** [comment]
I've made a start on this: https://github.com/Lullabot/lubot/blob/drupalize.me/scripts/hackpad.js

It's running on the dmenodebot in #drupalizeme on freenode

Create a new hackpad:

```
lubot: make me a hackpad
```

Search hackpads: (returns up to 10 results via pm)

```
lubot: hackpad <search terms>
```
