### ISSUE TITLE
clearly document mongodb setup

### ISSUE THREAD

**Issue by sirkitree** [Lullabot/lubot#21]
I don't think we need to document the actual mongo db setup, but we should put some commands in the readme to get people started on their locals with a database and such. I'm still lost on getting this sucker connected to a local mongo db.

**Comment by eojthebrave** [comment]
I'm going to close this issue. We've got documentation about starting and connecting to mongodb in our README now, which I think is probably good enough. Feel free to re-open if you're looking for more than what is there.
