### ISSUE TITLE
Add a way for code to process an event that no other script has responded to

### ISSUE THREAD

**Issue by eojthebrave** [Lullabot/lubot#31]
**Problem**

I would like to have a way to listen for events that no other script has replied to in order to perform a second phase of event processing.

Right now, you can register a listener for any event, and when that event is triggered all listeners fire and have a chance to do their thing. But I want to have way to say, after all listeners have fired, if none of them actually did anything with the event, give me another go at it.

**Motivation**

This will allow for creating a smarter bot that can use natural language processing to infer intent from a sentence and then map that intent to an action. If someone types in a message that doesn't map exactly to a known pattern we can still try and do some processing on it to try and figure out what pattern they are trying to match.

This way people aren't required to remember some esoteric pattern that magically triggers a response/reaction from the bot.

Take for example the following:

```
bot: tacos?
bot: what is a taco?
bot: describe taco
bot: tell me about tacos
bot:  what do you know about tacos?
```

These represent 5 different ways of asking the same question. And their are probably a whole lot more that I'm not thinking of right now. But right now, our bot is only capable of responding to the first.

Or

```
bot: where is joe?
bot: seen joe?
bot: have you seen joe?
bot: when was joe last here?
```

Same question, different syntax.

If we have a way of capturing those messages that are addressed to the bot but for which there is no direct response we can then attempt to do some natural language processing on the string of text and possibly extract the requester's intent. We can then use that intent to map the original request to known good format for asking the question.

Example:

bot: where is joe? > no response > parse and find intent > intent === seen > bot: seen joe? > response

I suppose we could just do natural language processing on all incoming messages, but that seems like it introduces extra unnecessary overhead when someone is following the correct pattern.

**Comment by eojthebrave** [comment]
Doing a little bit of thinking out-loud here. I've been exploring https://wit.ai/ as a natural language processor. The idea being that when the bot gets a message it runs through all the plugins that are enabled. If none of them responds to the message the message is passed on to the wit.ai parser which also attempts to decipher the message and assign it an intent. If the parser is able to determine an intent then we can all the appropriate function after massaging the message a bit so that it will actually be able to respond appropriately.

You register an intent processor, `bot.registerIntentProcessor(function() { // ... });`

You register an intent handler, `bot.registerIntentHandler('factoid', function() { // ... });`

When the bot receives a message it calls all known intent processors and any one of them can optionally set the intent of a message.

And intent looks like this:

```json
{
 "_text": "have you seen eojthebrave recently?",
 "intent": "seen",
 "entities": {
  "contact": [
   {
    "value": "eojthebrave"
   }
  ]
 },
 "confidence": 0.85
}
```

or

```json
{
 "_text": "tacos?",
 "intent": "factoid",
 "entities": {
  "contact": [
   {
    "query": "tacos"
   }
  ]
 },
 "confidence": 0.82
}
```

or

```json
{
 "_text": "tacos are awesome",
 "intent": "factoid",
 "entities": {
  "contact": [
   {
    "query": "tacos",
    "value": "are awesome"
   }
  ]
 },
 "confidence": 0.62
}
```

_text: is the message that was passed in to the handler
intent: is a string representation of the intent, this should also map to a known intent handler
entites: is an array of key value pairs that the intent processor wishes to pass on to the intent handler
confidence: is a float, 0 to 1 that represents the level of confidence the intent processor has that it has correctly determined the intent of the message.

When an intent is received, check to see if the confidence value is at or above the current threshold, and if so, call the intent handler, passing it the intent object.

If no intent is received, AND the message is addressed to the bot directly, the message is passed to wit.ai. Which also tries to assign an intent, in the same format as above. If it does, we can call the intent handler. If it does not, finally we can just pass and not respond to the message.

We could also just decide to pass every message to wit and not have to deal with the slightly awkward flow here. You would then just register an intent handler that would get called anytime wit returns your intent. But I like that this allows us to parse all messages locally, and respond if we can, but then use the AI for messages sent to the bot.

**Comment by m4olivei** [comment]
> Is the requirement of calling complete() or complete(true) in your callback weird?
> Can you think of other ways I might be able to solve this problem of wanting to know if no-one responded to a message# event?

I like your other idea of using `bot.irc.events('message#');` to collect those event handlers, then unregister them, then emit them yourself and do the language processing after.  That way all the commands are not coupled with the language processing stuff.

I also agree with you in that sending all messages off to a language processing service is not ideal.  Better to let the simple text matching stuff have a go first.  For the usual reasons of what if the service is down, or one day goes away completely.

Question: Where doe the original intent object come from before sending to wit.ai?  Would the existing code need to change to that format?

This is some really cool stuff @eojthebrave!

**Comment by eojthebrave** [comment]
I've got this mostly working, though in a very ... uhm ... experimental state?

Here's my work in progress. https://github.com/Lullabot/lubot/tree/eojthebrave-flow

I tried to use the method of unregistering all bot.irc.events() and calling them on my own, but it doesn't really work out well because in order for this kind of flow to work you need to separate the code that determines wether or not you want to respond to a specific command from the code that actually responds. This allows us to use either our own local JS, or wit.ai, to determine if a response required, and then either one can dispatch to the code that provides the response.

I updated the factoid command so that it will work with wit.ai's intent processor using the workflow described above.

To answer your question about the intent object. My thinking is that we standardize on the format the wit.ai uses. Our local processor can attempt to infer intent from a message and create an intent object. If that doesn't work we can pass the whole message string to wit, which will also attempt to infer intent and create an intent object.

If you want to test this you'll need to add the `LUBOT_WIT_ACCESS` env variable, which is an API key for accessing wit.ai. (Ping me in IRC and I can give you mine). I'll also look at figuring out how to add you to the wit.ai project I have setup.

**Comment by eojthebrave** [comment]
P.S. There is a lot of documentation in the code about how this works, but I haven't updated the readme yet since I'm not 100% sure this is the right direction. But, if we do like this route I'll update our documentation to include information about how to provide your own commands.

**Comment by eojthebrave** [comment]
Oh yeah, and ... this shit totally works. It's kind of awesome.

![eojthebrave on freenode irc network eojthebrave 1 users ns 2015-02-05 08-26-41](https://cloud.githubusercontent.com/assets/17613/6062924/b6e3812c-ad10-11e4-8988-0dcaeea0ecfc.png)

Example wit.ai interface for configuring intent processors and then teaching the AI overlords ...

![console 2015-02-05 08-27-54](https://cloud.githubusercontent.com/assets/17613/6062948/e2c1b804-ad10-11e4-972b-99cef1f61d8b.png)

**Comment by q0rban** [comment]
That's rad!

**Comment by m4olivei** [comment]
Sweet!

**Comment by sirkitree** [comment]
Can we merge this? It really seems pretty sweet.

**Comment by willwh** [comment]
It totally is :+1:

**Comment by eojthebrave** [comment]
It should probably be tested by someone other than me before it gets merged.

And, we should probably have some kind of kill switch so that it can still operate if we turn wit.ai off, or don't want to use wit.ai anymore. And, might be worth it to ensure there is some kind of failover in place if wit.ai is down/not-responding or something like that.

**Comment by eojthebrave** [comment]
Oh, and the README.md documentation still needs to be updated so others can figure out how to write scripts/plugins to do new things with the new method of registering message handlers that this feature requires.
