### ISSUE TITLE
Add POST endpoint for channels

### ISSUE THREAD

**Issue by willwh** [Lullabot/lubot#45]
We need a generic POST handler for posting channel messages from external sources

**Comment by willwh** [comment]
Example POST:

curl -H "Content-Type: application/json" -X POST -d '{"token":"YOUR_TOKEN","message":"this is a POST message from somewhere","channel":"#drupalizeme"}' http://bot_url:process.env.PORT/drupalizeme

Should clean this up for a more generic endpoint

**Comment by willwh** [comment]
curl -H "Content-Type: application/json" -X POST -d '{"token":"YOUR_TOKEN","message":"this is a POST message from somewhere","channel":"#drupalizeme"}' http://bot_url:process.env.PORT/post0r

**Comment by q0rban** [comment]
:+1: this would be really cool!

**Comment by eojthebrave** [comment]
Fancy! This is working on d.me now, we're using this feature, combined with this module https://github.com/DrupalizeMe/dmesite/blob/dev/docroot/sites/all/modules/custom/dmebot/dmebot.module, to bounce messages to our channel from Recurly. Pretty cool.

![eojthebrave on freenode irc network drupalizeme 14 users cknt 2015-05-01 13-59-29](https://cloud.githubusercontent.com/assets/17613/7436364/49ed74f0-f00a-11e4-92f6-fab8f4b74353.jpg)

**Comment by willwh** [comment]
Closing :D
