### ISSUE TITLE
Voice Recognition

### ISSUE THREAD

**Issue by sirkitree** [Lullabot/lubot#47]
I know this sounds crazy but how cool would some sort of integration with https://wit.ai/ be?

**Comment by eojthebrave** [comment]
Impossible. Err no wait. I already did that. https://github.com/Lullabot/lubot/issues/31 - and https://github.com/Lullabot/lubot/tree/eojthebrave-flow

:+1:

**Comment by sirkitree** [comment]
daaamn. totally forgot about that thread :)
