### ISSUE TITLE
regex tidy up :)

### ISSUE THREAD

**Issue by willwh** [Lullabot/lubot#48]
@m4olivei I would love some regex advice :)

https://github.com/Lullabot/lubot/blob/drupalize.me/lubot.js#L168

https://github.com/Lullabot/lubot/blob/drupalize.me/lubot.js#L176

https://regex101.com/r/pG5uB3/1

Ideally, we would not be matching on say; +++++++++++, but only instances of ++

**Comment by q0rban** [comment]
I think if someone does +++++++, you still match it, but strip the extra +es. So, you'd just do `\+{2,}`, right?

**Comment by m4olivei** [comment]
I agree with @q0rban, not sure it matters to limit the number of "+"'s used.  In which case the regex is good, will match correctly and capture the username.  I noticed some slack username, (eg. t-bot) have dashes, so regex would miss those.  Also a couple other cleanup:

https://regex101.com/r/pG5uB3/4

If you wanted to match only two "+"s, here's one that could work.  It works by requiring a character that isn't a "+" after the first two, or the end of line position:

https://regex101.com/r/pG5uB3/2

**Comment by q0rban** [comment]
Good catch on the -. I think that means we'd also want other characters too, like underscores and … what else?

**Comment by q0rban** [comment]
I think there are some other scenarios we need to account for:

```
something nifty++
something_nifty++
tlattimore|afk++
[tlattimore]++
this shouldn't be a match for willwh++
we don't want $i++ to increment a karma value for i
thisiswaytoolongandshouldnotgetmatched++
```

**Comment by m4olivei** [comment]
Here's an error message I get when I try to change my name so something with all kinds of characters:

![image](https://cloud.githubusercontent.com/assets/191049/7774452/9914be92-0079-11e5-9d05-93c2da2bfac7.png)

I'll make a PR to correct some of these regex's.  Will need getting my local setup for testing though.

**Comment by q0rban** [comment]
Remember, you can give karma to things other than just people:

```
[12:02:53]  <q0rban>    ie6--
[12:02:54]  <lullabot>  ie6 has karma of -22.
```

**Comment by m4olivei** [comment]
Right, and now that I read through the whole diff, seems like you were thinking about just users @willwh ?

**Comment by m4olivei** [comment]
Tried something that makes sense in my head in a5b85a2.  Need to test though and I can't get the node server to start locally on this branch anymore :/.

**Comment by willwh** [comment]
I pushed some updates specific to my setup, so it doesn't even allow http
connections. I'll hook up with you this afternoon and I can push something
you can work with.

That Drupalize.me branch is dirty ATM ;)

**Comment by m4olivei** [comment]
Cool, ping me whenever.

**Comment by m4olivei** [comment]
Calling this guy closed.  Going to open more specific issues as they come.
